### ISSUE TITLE
App crashes on Android targetSdkVersion >=34

### ISSUE THREAD

**Issue by RB-93** [25LucasAnselmo/gr_zoom#18]
Issue found in version:

> gr_zoom: ^1.3.0+1

```
var zoom = Zoom();
await zoom.init(zoomOptions).then((results) async {
        print(results[0]);
        if (results[0] == 0) {
          zoom.onMeetingStateChanged.listen((status) {
            print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
          });
          print("listen on event channel");
          await zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
            print('joinMeetingResult');
            print(joinMeetingResult);
          }).catchError((error, stackTrace) {
            print('error');
            print(error);
          });
        }
      }).catchError((error) {
        print("[Error Generated] : " + error);
      });
```

Steps to reproduce:
1. Try joining using above code.
2. App prompts for dialog permissions
3. Keep allowing each one.
4. App crashes with the following log..

`
I/flutter ( 7608): 0
I/flutter ( 7608): listen on event channel
I/flutter ( 7608): joinMeetingResult
I/flutter ( 7608): true
D/AppCompatDelegate( 7608): Checking for metadata for AppLocalesMetadataHolderService : Service not found
I/an.samvaad.test( 7608): Background concurrent copying GC freed 503365(12MB) AllocSpace objects, 8(416KB) LOS objects, 50% free, 23MB/47MB, paused 301us,40us total 167.600ms
D/FlutterBranchSDK( 7608): triggered onActivityStarted
W/an.samvaad.test( 7608): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/an.samvaad.test( 7608): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
I/CameraManagerGlobal( 7608): Connecting to camera service
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 7608): [soar.cts] ignore the status update of camera: 2
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 7608): [soar.cts] ignore the status update of camera: 3
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 7608): [soar.cts] ignore the status update of camera: 4
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 7608): ignore the torch status update of camera: 3
W/libc    ( 7608): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 7608): ignore the torch status update of camera: 4
D/CompatibilityChangeReporter( 7608): Compat change id reported: 147600208; UID 10293; state: ENABLED
I/matt    ( 7608): get GetAndroidCtrlInfo failed
W/an.samvaad.test( 7608): type=1400 audit(0.0:1331689): avc:  denied  { read } for  name="usb" dev="tmpfs" ino=12431 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=0 app=com.kisan.samvaad.test
W/an.samvaad.test( 7608): type=1400 audit(0.0:1331690): avc:  denied  { read } for  name="/" dev="tmpfs" ino=3 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0 app=com.kisan.samvaad.test
W/AudioTrack( 7608): Use of stream types is deprecated for operations other than volume control
W/AudioTrack( 7608): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/OpenGLRenderer( 7608): --- Failed to create image decoder with message 'unimplemented'
D/CompatibilityChangeReporter( 7608): Compat change id reported: 171228096; UID 10293; state: ENABLED
I/an.samvaad.test( 7608): Background young concurrent copying GC freed 400722(10MB) AllocSpace objects, 16(576KB) LOS objects, 20% free, 37MB/47MB, paused 198us,119us total 106.210ms
D/CompatibilityChangeReporter( 7608): Compat change id reported: 210923482; UID 10293; state: ENABLED
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
I/an.samvaad.test( 7608): Background concurrent copying GC freed 1014205(26MB) AllocSpace objects, 0(0B) LOS objects, 48% free, 25MB/49MB, paused 76us,41us total 162.624ms
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/FlutterBranchSDK( 7608): triggered onActivityStarted
D/BLASTBufferQueue( 7608): [VRI[ZmConfActivity]#2](f:0,a:0) HMDCF: update width=720 height=1612 format=-1 mTransformHint=0
D/BufferQueueConsumer( 7608): [VRI[ZmConfActivity]#2(BLAST Consumer)2](id:1db800000002,api:0,p:0,c:7608) HMDCF: setDefaultBufferSize: width=720 height=1612
E/OpenGLRenderer( 7608): Unable to match the desired swap behavior.
I/flutter ( 7608): [Meeting Status Stream] : MEETING_STATUS_CONNECTING - Connect to the meeting server.
D/FlutterBranchSDK( 7608): triggered onActivityStopped
D/FlutterBranchSDK( 7608): triggered onActivityStopped
D/FlutterBranchSDK( 7608): triggered onActivityDestroyed
W/WindowOnBackDispatcher( 7608): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 7608): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/BLASTBufferQueue( 7608): [VRI[ZmConfActivity]#3](f:0,a:0) HMDCF: update width=832 height=716 format=-2 mTransformHint=0
D/BufferQueueConsumer( 7608): [VRI[ZmConfActivity]#3(BLAST Consumer)3](id:1db800000003,api:0,p:161,c:7608) HMDCF: setDefaultBufferSize: width=832 height=716
E/OpenGLRenderer( 7608): Unable to match the desired swap behavior.
I/FA      ( 7608): Application backgrounded at: timestamp_millis: 1714995499381
D/CompatibilityChangeReporter( 7608): Compat change id reported: 78294732; UID 10293; state: ENABLED
D/OpenGLRenderer( 7608): --- Failed to create image decoder with message 'unimplemented'
D/BLASTBufferQueue( 7608): [VRI[ZmConfActivity]#2](f:0,a:1) HMDCF: update width=720 height=1612 format=-1 mTransformHint=0
D/CompatibilityChangeReporter( 7608): Compat change id reported: 163400105; UID 10293; state: ENABLED
I/ImeTracker( 7608): com.kisan.samvaad.test:96559033: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
W/InputMethodManager( 7608): view.getId() 2131363266   photosId:2131432073
D/InputMethodManager( 7608): showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{cafbb63 VFED..CL. .F.P.... 56,175-664,256 #7f0a05c2 app:id/edtScreenName aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
I/AssistStructure( 7608): Flattened final assist data: 11244 bytes, containing 3 windows, 84 views
D/BLASTBufferQueue( 7608): [VRI[PopupWindow:930f8c1]#4](f:0,a:0) HMDCF: update width=70 height=70 format=-3 mTransformHint=0
D/BufferQueueConsumer( 7608): [VRI[PopupWindow:930f8c1]#4(BLAST Consumer)4](id:1db800000004,api:0,p:0,c:7608) HMDCF: setDefaultBufferSize: width=70 height=70
E/OpenGLRenderer( 7608): Unable to match the desired swap behavior.
I/ImeTracker( 7608): com.kisan.samvaad.test:b68e89ff: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
W/InputMethodManager( 7608): view.getId() 2131363266   photosId:2131432073
D/InputMethodManager( 7608): showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{cafbb63 VFED..CL. .F...... 56,175-664,256 #7f0a05c2 app:id/edtScreenName aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
W/WindowOnBackDispatcher( 7608): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@935ffd
D/InsetsController( 7608): show(ime(), fromIme=true)
D/BLASTBufferQueue( 7608): [VRI[PopupWindow:930f8c1]#5](f:0,a:0) HMDCF: update width=70 height=70 format=-3 mTransformHint=0
D/BufferQueueConsumer( 7608): [VRI[PopupWindow:930f8c1]#5(BLAST Consumer)5](id:1db800000005,api:0,p:776304152,c:7608) HMDCF: setDefaultBufferSize: width=70 height=70
E/OpenGLRenderer( 7608): Unable to match the desired swap behavior.
D/InsetsController( 7608): show(ime(), fromIme=true)
I/ImeTracker( 7608): com.kisan.samvaad.test:b68e89ff: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
I/ImeTracker( 7608): com.kisan.samvaad.test:96559033: onShown
W/WindowOnBackDispatcher( 7608): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@f489431
I/ImeTracker( 7608): com.kisan.samvaad.test:63025a8e: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
W/InputMethodManager( 7608): view.getId() 2131363241   photosId:2131432073
D/InputMethodManager( 7608): showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{37d2360 VFED..CL. .F.P..ID 56,284-664,365 #7f0a05a9 app:id/edtEmail aid=1073741825} flags=0 reason=SHOW_SOFT_INPUT
W/RemoteInputConnectionImpl( 7608): requestCursorAnchorInfo on inactive InputConnection
W/WindowOnBackDispatcher( 7608): sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@234342946 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@f747b4d
D/InsetsController( 7608): show(ime(), fromIme=true)
I/ImeTracker( 7608): com.kisan.samvaad.test:5c27e9d0: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
D/InsetsController( 7608): show(ime(), fromIme=true)
I/ImeTracker( 7608): com.kisan.samvaad.test:63025a8e: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
I/ImeTracker( 7608): com.kisan.samvaad.test:bbd42d80: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
W/WindowOnBackDispatcher( 7608): sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@234342946 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@a27d1bd
W/WindowOnBackDispatcher( 7608): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@e6083c9
W/WindowOnBackDispatcher( 7608): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 7608): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
W/RemoteInputConnectionImpl( 7608): requestCursorAnchorInfo on inactive InputConnection
I/ImeTracker( 7608): com.kisan.samvaad.test:bbd42d80: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
E/ImeBackDispatcher( 7608): Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 234342946
I/System.out( 7608): On meeting parameter notification
W/WindowOnBackDispatcher( 7608): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 7608): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/OpenGLRenderer( 7608): --- Failed to create image decoder with message 'unimplemented'
I/Choreographer( 7608): Skipped 56 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 7608): Skipped 31 frames!  The application may be doing too much work on its main thread.
W/an.samvaad.test( 7608): Cleared Reference was only reachable from finalizer (only reported once)
D/BLASTBufferQueue( 7608): [VRI[ZmConfActivity]#2](f:0,a:1) HMDCF: update width=720 height=1612 format=-1 mTransformHint=0
D/SurfaceTexture( 7608): HMDCB setDefaultBufferSize + 720 x 1480 by android.view.TextureView.getTextureLayer:466 android.view.TextureView.draw:419 android.view.View.updateDisplayListIfDirty:22793 android.view.View.draw:23657 android.view.ViewGroup.drawChild:4556
D/BufferQueueConsumer( 7608): [SurfaceTexture-0-7608-0](id:1db800000006,api:0,p:552439636,c:7608) HMDCF: setDefaultBufferSize: width=720 height=1480
W/WindowOnBackDispatcher( 7608): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 7608): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
W/an.samvaad.test( 7608): type=1400 audit(0.0:1331691): avc:  denied  { ioctl } for  path="socket:[35788091]" dev="sockfs" ino=35788091 ioctlcmd=0x8927 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tclass=udp_socket permissive=0 app=com.kisan.samvaad.test
W/an.samvaad.test( 7608): type=1400 audit(0.0:1331692): avc:  denied  { ioctl } for  path="socket:[35788091]" dev="sockfs" ino=35788091 ioctlcmd=0x8927 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tclass=udp_socket permissive=0 app=com.kisan.samvaad.test
W/Thread-24( 7608): type=1400 audit(0.0:1331693): avc:  denied  { ioctl } for  path="socket:[35777330]" dev="sockfs" ino=35777330 ioctlcmd=0x8927 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tclass=udp_socket permissive=0 app=com.kisan.samvaad.test
W/Thread-24( 7608): type=1400 audit(0.0:1331694): avc:  denied  { ioctl } for  path="socket:[35777330]" dev="sockfs" ino=35777330 ioctlcmd=0x8927 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tclass=udp_socket permissive=0 app=com.kisan.samvaad.test
W/WindowOnBackDispatcher( 7608): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 7608): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
D/skia    ( 7608): computeOutputColorType requestedColorType 4, encode format 4 colorDepth 8
I/AudioManager( 7608): In isBluetoothScoAvailableOffCall(), calling appilication: com.kisan.samvaad.test, return value: true
I/AudioManager( 7608): In setSpeakerphoneOn(), on: true, calling application: com.kisan.samvaad.test
W/AudioTrack( 7608): Use of stream types is deprecated for operations other than volume control
W/AudioTrack( 7608): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/AudioManager( 7608): In isBluetoothScoAvailableOffCall(), calling appilication: com.kisan.samvaad.test, return value: true
I/AudioManager( 7608): In setSpeakerphoneOn(), on: true, calling application: com.kisan.samvaad.test
I/Choreographer( 7608): Skipped 93 frames!  The application may be doing too much work on its main thread.
D/SurfaceTexture( 7608): HMDCB setDefaultBufferSize + 240 x 370 by android.view.TextureView.getTextureLayer:466 android.view.TextureView.draw:419 android.view.View.updateDisplayListIfDirty:22793 android.view.View.draw:23657 android.view.ViewGroup.drawChild:4556
D/BufferQueueConsumer( 7608): [SurfaceTexture-0-7608-1](id:1db800000007,api:0,p:0,c:7608) HMDCF: setDefaultBufferSize: width=240 height=370
E/libEGL  ( 7608): call to OpenGL ES API with no current context (logged once per thread)
I/OpenGLRenderer( 7608): Davey! duration=1130ms; Flags=0, FrameTimelineVsyncId=320077367, IntendedVsync=1718243244017025, Vsync=1718244280029306, InputEventId=0, HandleInputStart=1718244285409570, AnimationStart=1718244285416289, PerformTraversalsStart=1718244285509153, DrawStart=1718244351162695, FrameDeadline=1718243505899143, FrameInterval=1718244284859987, FrameStartTime=11139917, SyncQueued=1718244360338216, SyncStart=1718244361692122, IssueDrawCommandsStart=1718244362845976, SwapBuffers=1718244373043320, FrameCompleted=1718244376119414, DequeueBufferDuration=28594, QueueBufferDuration=671875, GpuCompleted=1718244376119414, SwapBuffersCompleted=1718244374214414, DisplayPresentTime=1718230622342752, CommandSubmissionCompleted=1718244373043320,
E/ThemeUtils( 7608): View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils( 7608): View class com.airbnb.lottie.LottieAnimationView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
D/CompatibilityChangeReporter( 7608): Compat change id reported: 236704164; UID 10293; state: ENABLED
I/flutter ( 7608): [Meeting Status Stream] : MEETING_STATUS_INMEETING - Meeting is ready and in process.
D/AndroidRuntime( 7608): Shutting down VM
E/AndroidRuntime( 7608): FATAL EXCEPTION: main
E/AndroidRuntime( 7608): Process: com.kisan.samvaad.test, PID: 7608
E/AndroidRuntime( 7608): java.lang.IllegalArgumentException: com.kisan.samvaad.test: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
E/AndroidRuntime( 7608): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
E/AndroidRuntime( 7608): 	at android.os.Parcel.createException(Parcel.java:3041)
E/AndroidRuntime( 7608): 	at android.os.Parcel.readException(Parcel.java:3024)
E/AndroidRuntime( 7608): 	at android.os.Parcel.readException(Parcel.java:2966)
E/AndroidRuntime( 7608): 	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6568)
E/AndroidRuntime( 7608): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:737)
E/AndroidRuntime( 7608): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:720)
E/AndroidRuntime( 7608): 	at us.zoom.internal.uvc.USBMonitor.e(USBMonitor.java:12)
E/AndroidRuntime( 7608): 	at us.zoom.internal.uvc.USBMonitor.start(USBMonitor.java:12)
E/AndroidRuntime( 7608): 	at us.zoom.proguard.kh0$d.onMeetingStatusChanged(InMeetingServiceImpl.java:2)
E/AndroidRuntime( 7608): 	at us.zoom.internal.impl.b$c.run(MeetingServiceImpl.java:5)
E/AndroidRuntime( 7608): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 7608): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7608): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 7608): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 7608): 	at android.app.ActivityThread.main(ActivityThread.java:8229)
E/AndroidRuntime( 7608): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7608): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 7608): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
E/AndroidRuntime( 7608): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 7608): 	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5519)
E/AndroidRuntime( 7608): 	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5462)
E/AndroidRuntime( 7608): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3251)
E/AndroidRuntime( 7608): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2843)
E/AndroidRuntime( 7608): 	at android.os.Binder.execTransactInternal(Binder.java:1344)
E/AndroidRuntime( 7608):
I/Process ( 7608): Sending signal. PID: 7608 SIG: 9
Lost connection to device.

Exited.
`

**Comment by 25LucasAnselmo** [comment]
In 1.2.0+5 the meeting works? This current update some plugin dependencies was updated, so some inconsistencies can happen. Youre sending jwtToken correctly?

**Comment by RB-93** [comment]
> In 1.2.0+5 the meeting works? This current update some plugin dependencies was updated, so some inconsistencies can happen. Youre sending jwtToken correctly?

Yes, it worked in 1.2.0+5
and sending JWTToken correctly.

**Comment by 25LucasAnselmo** [comment]
> > In 1.2.0+5 the meeting works? This current update some plugin dependencies was updated, so some inconsistencies can happen. Youre sending jwtToken correctly?
> 
> Yes, it worked in 1.2.0+5 and sending JWTToken correctly.

Got it. Try to use 1.2.0+5 for now, i'll look about this on next update

**Comment by gm6534** [comment]
Hi @25LucasAnselmo,

When will you update? Also i encountered app crash on Android 14 with version 1.3.0+1 of gr_zoom.


**Console Log**

Shutting down VM
E/AndroidRuntime(15297): FATAL EXCEPTION: main
E/AndroidRuntime(15297): java.lang.IllegalArgumentException: com.autosmarttech.interpretingApp: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
E/AndroidRuntime(15297): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3091)
E/AndroidRuntime(15297): 	at android.os.Parcel.createException(Parcel.java:3071)
E/AndroidRuntime(15297): 	at android.os.Parcel.readException(Parcel.java:3054)
E/AndroidRuntime(15297): 	at android.os.Parcel.readException(Parcel.java:2996)
E/AndroidRuntime(15297): 	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6568)
E/AndroidRuntime(15297): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:735)
E/AndroidRuntime(15297): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:718)
E/AndroidRuntime(15297): 	at us.zoom.internal.uvc.USBMonitor.e(USBMonitor.java:12)
E/AndroidRuntime(15297): 	at us.zoom.internal.uvc.USBMonitor.start(USBMonitor.java:12)
E/AndroidRuntime(15297): 	at us.zoom.proguard.kh0$d.onMeetingStatusChanged(InMeetingServiceImpl.java:2)
E/AndroidRuntime(15297): 	at us.zoom.internal.impl.b$c.run(MeetingServiceImpl.java:5)
E/AndroidRuntime(15297): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(15297): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15297): 	at android.os.Looper.loopOnce(Looper.java:257)
E/AndroidRuntime(15297): 	at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(15297): 	at android.app.ActivityThread.main(ActivityThread.java:8826)
E/AndroidRuntime(15297): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15297): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(15297): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(15297): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(15297): 	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5908)
E/AndroidRuntime(15297): 	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5851)
E/AndroidRuntime(15297): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3251)
E/AndroidRuntime(15297): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3005)
E/AndroidRuntime(15297): 	at android.os.Binder.execTransactInternal(Binder.java:1392)
E/AndroidRuntime(15297): 
I/Process (15297): Sending signal. PID: 15297 SIG: 9

**Comment by 25LucasAnselmo** [comment]
Try to use gr_zoom: 1.3.0 version

**Comment by 25LucasAnselmo** [comment]
Hi! I will update zoom sdk android to 5.17.11 version on next week. The current version works fine on android 14 here, but, ill try resolve this with the update. Check the Zoom Sdk Releases:

https://developers.zoom.us/changelog/meeting-sdk/
